using Mesher.Model;
using System;
using System.Collections.Generic;
using System.Text;

namespace Mesher.Geometry {

	class Mesh {

		// nullable
		// when non-null, this is generated by a particular body part
		// when null, this is made up of multiple meshes
		BodyPart owner;

		List<Face> faces;

		public Mesh(BodyPart owner, List<Face> faces) {
			this.owner = owner;
			this.faces = faces;
		}

		public Mesh(List<Mesh> meshes) {
			faces = new List<Face>();
			foreach(Mesh mesh in meshes)
				faces.AddRange(mesh.faces);
		}

		public Mesh() {
			faces = new List<Face>();
		}

		public void Add(Mesh mesh) {
			faces.AddRange(mesh.faces);
		}
	}
}
